# .github/workflows/build-rockpi4c.yml
name: Build RockPi4C Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # Weekly: Monday 02:00 UTC

jobs:
  build-all-editions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        edition: [minimal, lxqt, kde-plasma, xfce]  # adjust as desired
        branch: [master]
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Checkout arm-profiles
        uses: actions/checkout@v4
        with:
          repository: felipehertzer/arm-profiles
          path: arm-profiles

      - name: Install required packages & tools
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static binfmt-support git wget debootstrap libarchive-tools pip3
          pip3 install lxml

      - name: Install manjaro-arm-tools
        run: |
          git clone https://gitlab.manjaro.org/manjaro-arm/applications/manjaro-arm-tools.git
          cd manjaro-arm-tools
          sudo cp bin/* /usr/bin/
          sudo cp lib/* /usr/share/manjaro-arm-tools/lib/
          sudo chmod +x /usr/bin/buildarmimg
          # Create needed directories
          for d in pkg img tmp; do sudo mkdir -p /var/lib/manjaro-arm-tools/$d; done
          for d in img pkg; do sudo mkdir -p /var/cache/manjaro-arm-tools/$d; done
          # Enable QEMU for ARM binaries
          sudo update-binfmts --enable qemu-aarch64

      - name: Install profiles
        run: |
          sudo mv arm-profiles /usr/share/manjaro-arm-tools/profiles

      - name: Build image for ${{ matrix.edition }}
        env:
          DEVICE: rockpi4c
          EDITION: ${{ matrix.edition }}
          BRANCH: ${{ matrix.branch }}
          VERSION: ${{ github.run_number }}
        run: |
          sudo buildarmimg -d $DEVICE -e $EDITION -b $BRANCH -v $VERSION

      - name: Locate generated image
        id: find
        run: |
          FILE=$(find /var/cache/manjaro-arm-tools/img -type f -name "*rockpi4c-*.img.xz" | head -n1)
          echo "FILE=$FILE" >> $GITHUB_ENV

      - name: Inspect artifact
        run: ls -lh "$FILE"

      - name: Create GitHub Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: img-${{ matrix.edition }}-${{ github.run_number }}
          name: RockPi4C – ${{ matrix.edition }} – build #${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload image asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ env.FILE }}
          asset_name: ${{ matrix.edition }}.img.xz
          asset_content_type: application/x-compressed-tar

      - name: Generate SHA1 checksum
        run: sha1sum "$FILE" > "${FILE}.sha1"

      - name: Upload SHA1 asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: "${{ env.FILE }}.sha1"
          asset_name: "${{ matrix.edition }}.img.xz.sha1"
          asset_content_type: text/plain
