name: Build and Release ARM Images

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      device:
        description: Device to build for, or the word all
        required: true
        default: rockpi4c
      edition:
        description: Edition to build (ignored when device is all)
        required: true
        default: xfce
      version:
        description: Version label (leave blank for auto)
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: |
          ${{ toJson(fromJSON(
            github.event_name == 'workflow_dispatch' && inputs.device == 'all' ?
            '[{"device":"rockpi4c","edition":"minimal"},{"device":"rockpi4c","edition":"xfce"},{"device":"rockpi4b","edition":"minimal"},{"device":"rockpi4b","edition":"xfce"},{"device":"rpi4","edition":"minimal"},{"device":"rpi4","edition":"xfce"}]' :
            format('[{{"device":"{0}","edition":"{1}"}}]', inputs.device, inputs.edition)
          )) }}
    env:
      DEVICE: ${{ matrix.device }}
      EDITION: ${{ matrix.edition }}
      VERSION: ${{ inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free disk
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo docker image prune --all --force
          sudo apt-get autoremove -y
          sudo apt-get autoclean

      - name: Base packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pacman arch-install-scripts \
            qemu-user-static binfmt-support \
            parted dosfstools git wget bsdtar haveged pwgen

      - name: Manjaro ARM Tools
        run: |
          sudo mkdir -p /usr/share/manjaro-arm-tools/lib
          git clone --depth 1 https://gitlab.manjaro.org/manjaro-arm/applications/manjaro-arm-tools.git
          sudo install -m755 manjaro-arm-tools/bin/* /usr/local/bin/
          sudo cp -r manjaro-arm-tools/lib/* /usr/share/manjaro-arm-tools/lib/

      - name: Profiles
        run: |
          sudo mkdir -p /usr/share/manjaro-arm-tools/profiles
          git clone --depth 1 https://gitlab.manjaro.org/manjaro-arm/applications/arm-profiles.git
          sudo cp -r arm-profiles/* /usr/share/manjaro-arm-tools/profiles/
          sudo ln -s /usr/share/manjaro-arm-tools/profiles /arm-profiles || true

      - name: Minimal configs
        run: |
          sudo install -d /etc/manjaro-arm-tools
          cat <<EOF | sudo tee /etc/manjaro-arm-tools/manjaro-arm-tools.conf
CARCH=aarch64
IMGDIR=/var/cache/manjaro-arm-tools/img
BUILDDIR=/var/lib/manjaro-arm-tools
PKGDIR=/var/cache/manjaro-arm-tools/pkg
COMPRESSION=xz
EOF
          cat <<EOF | sudo tee /etc/makepkg.conf
CARCH=aarch64
CHOST=aarch64-unknown-linux-gnu
MAKEFLAGS="-j$(nproc)"
PKGEXT='.pkg.tar.xz'
SRCEXT='.src.tar.gz'
EOF

      - name: Build version
        id: ver
        run: |
          if [ -z "$VERSION" ]; then
              if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
                  VERSION=${{ github.ref_name }}; VERSION=${VERSION#v}
              else
                  VERSION=$(date +%Y.%m)
              fi
          fi
          echo "value=$VERSION" >>"$GITHUB_OUTPUT"

      - name: Build image
        run: |
          sudo buildarmimg -d "$DEVICE" -e "$EDITION" -v "${{ steps.ver.outputs.value }}"

      - name: Compress
        run: |
          cd /var/cache/manjaro-arm-tools/img
          IMG=$(ls -t *.img | head -1)
          xz -z -T0 "$IMG"
          echo "FILE=${IMG}.xz" >>"$GITHUB_ENV"

      - name: Checksums
        run: |
          cd /var/cache/manjaro-arm-tools/img
          sha256sum "$FILE" >"$FILE.sha256"
          md5sum   "$FILE" >"$FILE.md5"

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DEVICE }}-${{ env.EDITION }}-${{ steps.ver.outputs.value }}
          path: |
            /var/cache/manjaro-arm-tools/img/${{ env.FILE }}
            /var/cache/manjaro-arm-tools/img/${{ env.FILE }}.sha256
            /var/cache/manjaro-arm-tools/img/${{ env.FILE }}.md5
          retention-days: 30

      - name: Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            /var/cache/manjaro-arm-tools/img/${{ env.FILE }}
            /var/cache/manjaro-arm-tools/img/${{ env.FILE }}.sha256
            /var/cache/manjaro-arm-tools/img/${{ env.FILE }}.md5
