name: Build RockPi4C Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        edition: [base, kde, xfce, lxqt, minimal]
        branch: [master]
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout arm-profiles
        uses: actions/checkout@v4
        with:
          repository: felipehertzer/arm-profiles
          token: ${{ secrets.GITHUB_TOKEN }}
          path: arm-profiles

      - name: Install dependencies
        run: |
          sudo pacman -Sy --noconfirm manjaro-arm-tools qemu-user-static arch-install-scripts

      - name: Set up profiles for buildarmimg
        run: |
          sudo mv arm-profiles /usr/share/manjaro-arm-tools/profiles
          sudo wget -qO /usr/lib/binfmt.d/qemu-static.conf \
            https://gitlab.manjaro.org/packages/community/manjaro-arm-qemu-static/-/raw/master/qemu-static.conf
          sudo service systemd-binfmt restart

      - name: Build image for ${{ matrix.edition }}
        env:
          DEVICE: rockpi4c
          EDITION: ${{ matrix.edition }}
          BRANCH: ${{ matrix.branch }}
          VERSION: ${{ github.run_number }}
        run: |
          sudo buildarmimg -d $DEVICE -e $EDITION -b $BRANCH -v $VERSION

      - name: Find generated image
        id: find
        run: |
          echo "FILE=$(find /var/cache/manjaro-arm-tools/img -type f -name '*rockpi4c-*.img.xz' | head -n 1)" >> $GITHUB_ENV

      - name: Verify artifact
        run: |
          ls -lh "$FILE"

      - name: Create release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: img-${{ matrix.edition }}-${{ github.run_number }}
          name: RockPi4C – ${{ matrix.edition }} – build #${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload image
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ env.FILE }}
          asset_name: ${{ matrix.edition }}.img.xz
          asset_content_type: application/x-compressed-tar

      - name: Upload SHA1
        run: |
          sha1sum "$FILE" > "${FILE}.sha1"
        env:
          FILE: ${{ env.FILE }}

      - name: Upload SHA1 asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: "${{ env.FILE }}.sha1"
          asset_name: ${{ matrix.edition }}.img.xz.sha1
          asset_content_type: text/plain
